#if !canImport(ObjectiveC)
import XCTest

extension ADTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ADTTests = [
        ("testBool", testBool),
        ("testInt", testInt),
        ("testMultiset", testMultiset),
        ("testNat", testNat),
    ]
}

extension EqProofTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EqProofTests = [
        ("testEquationalProof", testEquationalProof),
        ("testZeroSumIdentity", testZeroSumIdentity),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ADTTests.__allTests__ADTTests),
        testCase(EqProofTests.__allTests__EqProofTests),
    ]
}
#endif
